### PR TITLE
Removed Einar from flake texture.

### LINKED ISSUE #19: Remove Einar from snowflake texture + more flake textures
Einar can't be on the flakes :cry:

Also, more might make the simulation look more dynamic

### PR DESCRIPTION
**Pull request by CarlEnglund**
Removed Einar. Should we have more textures for the flakes? Or maybe that's something we can do for a later release. Fixes #19

### CODE REVIEW

**Comment by klaseskilson** [comment]
Is it only me, or is there still a circle-shaped shadow around the center of the snowflake?

**Comment by tistatos** [comment]
Yes, I see the circle as well.

Regarding the multiple snow flakes: would be nice  to have different but I'd say it isn't necessary now. But when we do, we need to have all flakes on one and the same texture due to the instancing. But we can just fix the particles to use different texture in the shader

**Comment by CarlEnglund** [comment]
My bad. How about now?

**Comment by klaseskilson** [comment]
Looks great! However, we do not want this to `master`, do we? Ready for merge!

**Pull request closed without merging**
